# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2ebfc7103fb02ae365fd688690f1357499a4f213413fc9e565665c9dfc8505507aab901130b859b93c6cd82c19e7ad02e3e127f86071d23e2f0663efd510a46

test:
  secret_key_base: a41b147341f698fafd396d99ec3fa8394e05e59bb444b6ab11218e18d1fd3dd6ad5f4ca5bd42858113b7b7902ddd0ea0735b6d0463756e5308d8b34e0a8907dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
